dataset: Sim_Sun
output_dir: '.'
z_dims: [2,2,2,4]
v_dim: 200
lr_theta: 0.0001
lr_z: 0.0001
x_min: 0
x_max: 3
g_units: [64,64,64,64,64]
e_units: [64,64,64,64,64]
f_units: [64,32,8]
h_units: [64,32,8]
save_res: True
save_model: True
binary_treatment: False
pretrain: True
lr: 0.0002
alpha: 1
beta: 1
gamma: 10
g_d_freq: 5
use_z_rec: True
e_units: [64,64,64,64,64]
dz_units: [64,32,8]